export const OBJECT_CREATION_START = 'OBJECT_CREATION_START';
export const OBJECT_CREATION_SUCCESS = 'OBJECT_CREATION_SUCCESS';
export const OBJECT_CREATION_FAIL = 'OBJECT_CREATION_FAIL';
export const OBJECT_CREATION_INIT = 'OBJECT_CREATION_INIT';

export const FETCH_LIST_START = 'FETCH_LIST_START';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAIL = 'FETCH_LIST_FAIL';
export const FETCH_LIST_INIT = 'FETCH_LIST_INIT';

export const FETCH_OTHERS_START = 'FETCH_OTHERS_START';
export const FETCH_OTHERS_SUCCESS = 'FETCH_OTHERS_SUCCESS';
export const FETCH_OTHERS_FAIL = 'FETCH_OTHERS_FAIL';
export const FETCH_OTHERS_INIT = 'FETCH_OTHERS_INIT';

export const FETCH_OBJECT_START = 'FETCH_OBJECT_START';
export const FETCH_OBJECT_SUCCESS = 'FETCH_OBJECT_SUCCESS';
export const FETCH_OBJECT_FAIL = 'FETCH_OBJECT_FAIL';
export const FETCH_OBJECT_INIT = 'FETCH_OBJECT_INIT';
